### ISSUE TITLE
firebase_options not defined

### ISSUE THREAD

**Issue by Safvana-Techvalley** [xeladu/flutter_push_notification#1]
Error: Error when reading 'lib/firebase_options.dart': No such file or directory
import 'package:flutter_push_notification/firebase_options.dart';
       ^
lib/main.dart:14:41: Error: Undefined name 'DefaultFirebaseOptions'.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
                                        ^^^^^^^^^^^^^^^^^^^^^^

**Comment by xeladu** [comment]
Hi, as mentioned in the article you need to add the Firebase project by yourself. Otherwise you would be using my Firebase instance and I could be charged money if you exceed any free limits.

Check the part "Firebase setup" on how to create your own Firebase project (it won't cost you anything but a credit card is required in the process).
Check the part "App setup" on how to link the code from this repo with your Firebase project. Then the error message should disappear and it should work.
